# Generated by Django 5.0.7 on 2024-07-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67, verbose_name='Viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Familiya')),
                ('passport', models.CharField(blank=True, max_length=9, null=True, verbose_name='Pasport')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefon raqami')),
                ('age', models.PositiveIntegerField(default=0)),
                ('is_paid_for_year', models.BooleanField(default=0)),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.region')),
            ],
        ),
    ]
